#! /bin/bash

echo "[DEBUG] Init generate cert and key"
openssl req -x509 -nodes -days 1 -newkey rsa:2048 -keyout nginx-selfsigned.key -out nginx-selfsigned.crt

echo "[DEBUG] Init generate Diffie–Hellman parameters"
openssl dhparam -out dhparam.pem 2048
